spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    show-sql: true

    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/auc
    username: postgres
    password: 1
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB

  mail:
    host: smtp.yandex.ru
    username:
    password:
    port: 465
    protocol: stmps
    debug: true